language: java
sudo: false
jdk:
  - oraclejdk8
  - openjdk7
install: true
script:
    if ( `javac -version 2>&1 | grep '1\.8\.0' > /dev/null` ); then
      mkdir -p xstream/profiles/coveralls;
      mkdir -p xstream-hibernate/profiles/coveralls;
      mvn -V -B -e clean package jacoco:report coveralls:jacoco;
    else
      mvn -V -B -e clean package;
    fi
cache:
    directories:
    - $HOME/.m2
