dist: trusty
language: java
sudo: false
jdk:
  - openjdk11
  - openjdk10
  - oraclejdk9
  - openjdk8
  - openjdk7
install: true
script:
    if [ "$TRAVIS_JDK_VERSION" == "oraclejdk9" ]; then
      export SETTINGS="-s .travis.settings.xml";
    fi;
    if [ "$TRAVIS_JDK_VERSION" == "openjdk8" ]; then
      mkdir -p xstream/profiles/coveralls;
      mkdir -p xstream-hibernate/profiles/coveralls;
      mvn -V -B -e clean package jacoco:report coveralls:report $SETTINGS;
    else
      mvn -V -B -e clean package $SETTINGS;
    fi
cache:
  directories:
    - $HOME/.m2
